version: '3.9'
services:
  web:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
      # - redis  # Thêm redis service vào phần depends_on để web service phụ thuộc vào Redis
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=example
      - DB_NAME=mydatabase
    

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      # - mysql_data:/var/lib/mysql
      - ./data/backup.sql:/docker-entrypoint-initdb.d/backup.sql:ro

  # redis:
  #   image: redis:latest  # Sử dụng image Redis từ Docker Hub
  #   ports:
  #     - "6378:6379"  # Map cổng 6379 của host vào cổng 6379 của container Redis
# volumes:
#   mysql_data: